// <auto-generated />
using System;
using CrmApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrmApp.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvisorContract", b =>
                {
                    b.Property<int>("ParticipantsId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipatedContractsId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantsId", "ParticipatedContractsId");

                    b.HasIndex("ParticipatedContractsId");

                    b.ToTable("AdvisorContract");

                    b.HasData(
                        new
                        {
                            ParticipantsId = 1,
                            ParticipatedContractsId = 1
                        },
                        new
                        {
                            ParticipantsId = 2,
                            ParticipatedContractsId = 1
                        },
                        new
                        {
                            ParticipantsId = 4,
                            ParticipatedContractsId = 2
                        },
                        new
                        {
                            ParticipantsId = 1,
                            ParticipatedContractsId = 3
                        });
                });

            modelBuilder.Entity("CrmApp.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BirthNumber")
                        .IsUnique();

                    b.ToTable("Advisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthNumber = "850202/5678",
                            Email = "petr.oboji@gmail.com",
                            FirstName = "Petr",
                            LastName = "Obojí",
                            Phone = "+420 987 654 321"
                        },
                        new
                        {
                            Id = 2,
                            BirthNumber = "920303/9999",
                            Email = "karel.ucastnik@gmail.com",
                            FirstName = "Karel",
                            LastName = "Účastník",
                            Phone = "+420 111 222 333"
                        },
                        new
                        {
                            Id = 3,
                            BirthNumber = "900101/0000",
                            Email = "pavel.prazdny@gmail.com",
                            FirstName = "Pavel",
                            LastName = "Prázdný",
                            Phone = "+420 555 666 777"
                        },
                        new
                        {
                            Id = 4,
                            BirthNumber = "980808/8888",
                            Email = "zaneta.spravcova@gmail.com",
                            FirstName = "Žaneta",
                            LastName = "Bývalá-Správcová",
                            Phone = "+420 333 444 555"
                        });
                });

            modelBuilder.Entity("CrmApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BirthNumber")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthNumber = "960101/1234",
                            Email = "jan.bezny@gmail.com",
                            FirstName = "Jan",
                            LastName = "Běžný",
                            Phone = "+420 123 456 789"
                        },
                        new
                        {
                            Id = 2,
                            BirthNumber = "955515/5555",
                            Email = "alena.prazdna@gmail.com",
                            FirstName = "Alena",
                            LastName = "Prázdná",
                            Phone = "+420 000 000 000"
                        },
                        new
                        {
                            Id = 3,
                            BirthNumber = "800505/1111",
                            Email = "stepan.byvaly@gmail.com",
                            FirstName = "Štěpán",
                            LastName = "Bývalý",
                            Phone = "+420 111 222 333"
                        });
                });

            modelBuilder.Entity("CrmApp.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EffectiveDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "ČSOB",
                            ManagerId = 1,
                            RegistrationNumber = "2026/001",
                            SignedDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 3,
                            EffectiveDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Komerční banka",
                            ManagerId = 4,
                            RegistrationNumber = "2024/099",
                            SignedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            EffectiveDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2035, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Kooperativa",
                            ManagerId = 1,
                            RegistrationNumber = "2026/002",
                            SignedDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AdvisorContract", b =>
                {
                    b.HasOne("CrmApp.Models.Advisor", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmApp.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ParticipatedContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrmApp.Models.Contract", b =>
                {
                    b.HasOne("CrmApp.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrmApp.Models.Advisor", "Manager")
                        .WithMany("ManagedContracts")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CrmApp.Models.Advisor", b =>
                {
                    b.Navigation("ManagedContracts");
                });

            modelBuilder.Entity("CrmApp.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
